# Generated by Django 6.0.6 on 2026-06-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moisture_threshold', models.FloatField(default=20.0)),
                ('temp_threshold', models.FloatField(default=35.0)),
            ],
        ),
    ]
