# Generated by Django 6.0.6 on 2026-06-16 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FertilizerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_trained', models.DateTimeField(auto_now=True)),
                ('model_version', models.CharField(default='1.0', max_length=50)),
            ],
        ),
    ]
