# Generated by Django 6.0.6 on 2026-06-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('IRRIGATION', 'Irrigation Advisory'), ('TEMPERATURE', 'Temperature Alert'), ('MOISTURE', 'Soil Moisture Alert')], max_length=20)),
                ('message', models.TextField()),
                ('severity', models.CharField(default='INFO', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
