# Generated by Django 6.0.6 on 2026-06-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('MOISTURE', 'Moisture'), ('TEMPERATURE', 'Temperature'), ('IRRIGATION', 'Irrigation'), ('PH', 'pH'), ('HUMIDITY', 'Humidity')], max_length=20),
        ),
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('CRITICAL', 'Critical'), ('WARNING', 'Warning'), ('INFO', 'Info')], default='INFO', max_length=10),
        ),
    ]
