# Generated by Django 6.0.6 on 2026-07-05 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_field_device_delete_farm'),
        ('telemetry', '0002_sensortelemetry_delete_sensorreading'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensortelemetry',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='farms.device'),
        ),
    ]
